#!/bin/bash

############################################################################################
# DEMULTIPLEXING
############################################################################################

# Run this script on each separate dataset received from the sequencing company (if applicable; e.g. samples re-done later, or additions later on)
# This demultiplexes all the samples per plate, and then creates a "combined_plates" folder, into which all samples are saved as .fq.gz files
# You should end up with: 
# your_dataproject_directory/stacksoutput/combined_plates/ready 
# This ready/ folder is used in the next script; aligning to a reference genome

# if you have outputs from different projects, combine the output files in each ready/ folder into one new combined folder, 
# and use that as your input for the next script. If this is the case, make a new barcodes/bothplates_pops.txt file for all those samples  

############################################################################################

############################################################################################
# Submit this script as a job using:

# qsub -v NUM_PLATES=2, BASE_DIR="/mnt/lustre/users/cvansteenderen/RADseq_crystallinum/data/Dean_all_spp/IcePlant.RawData" 1_demultiplex.job

# BASE_DIR should have the barcodes/ plate_1/ plate_2 etc. folders

############################################################################################

#PBS -l select=1:ncpus=24:mpiprocs=24
#PBS -P CBBI1682
#PBS -q serial
#PBS -l walltime=36:00:00
#PBS -o /mnt/lustre/users/cvansteenderen/RADseq_crystallinum/data/Dean_all_spp/IcePlant.RawData/stacksoutput/demux_stdout.txt
#PBS -e /mnt/lustre/users/cvansteenderen/RADseq_crystallinum/data/Dean_all_spp/IcePlant.RawData/stacksoutput/demux_stderr.txt
#PBS -N stacks_demux
#PBS -M vsteenderen@gmail.com
#PBS -m abe

##############################################################################################

module add chpc/BIOMODULES
module add stacks

# Check if NUM_PLATES is set
if [ -z "$NUM_PLATES" ]; then
    echo "ERROR: NUM_PLATES variable is not set. Please provide it with '-v NUM_PLATES=<n>' when submitting the job."
    exit 1  # Exit with an error code
fi

NUM_PLATES=$NUM_PLATES

###############################################################################################
# DEMULTIPLEXING
###############################################################################################

echo "Demultiplexing for $NUM_PLATES plates..."

BASE_DIR=$BASE_DIR
cd "$BASE_DIR"

# Make sure you have created a "barcodes" folder, which contains internal index and population files. It HAS TO BE CALLED barcodes/
# E.g. if only one plate, then you should have: barcodes/internal_indexes_plate_1 and barcodes/pops_all.txt

# NB: here we automatically create the stacksoutput/ folder
mkdir -p "$BASE_DIR/stacksoutput"

# Loop through the number of plates (1, 2, or more plates)
for plate in $(seq 1 "$NUM_PLATES"); do
    PLATE_DIR="plate_$plate"
    
    if [ -d "$PLATE_DIR" ]; then
        echo "Demultiplexing $PLATE_DIR..."
        
        # Set the corresponding barcode file
        BARCODE_FILE="./barcodes/internal_indexes_plate_${plate}.txt"
        OUTPUT_DIR="./stacksoutput/plate_${plate}"
		
		mkdir -p $OUTPUT_DIR
        
        # Run process_radtags for each plate
		# See https://catchenlab.life.illinois.edu/stacks/comp/process_radtags.php for parameter settings
		
        process_radtags -P -p ./$PLATE_DIR -b $BARCODE_FILE -o $OUTPUT_DIR -c -q -r -D -t 140 --inline_inline --renz_1 mspI --renz_2 ecoRI --barcode-dist-2 2 --filter-illumina
    else
        echo "Warning: Directory $PLATE_DIR does not exist. Skipping..."
    fi
done

###############################################################################################
# POST-PROCESSING
###############################################################################################

echo "Post-processing for $NUM_PLATES plates..."

cd "$BASE_DIR/stacksoutput"

##############################################################
# Create a combined folder and copy files over from all plates
##############################################################

# Create a folder for all samples called "combined_plates"
# This will house all the samples from all plates in one folder 
mkdir -p combined_plates

# Loop through the plates and copy the files
# the line below is the same loop, but in one line that can be run directly in the terminal if you don't want to submit the job 
# NUM_PLATES=2; for plate in $(seq 1 "$NUM_PLATES"); do PLATE_DIR="plate_${plate}"; if [ -d "$PLATE_DIR" ]; then cp "$PLATE_DIR"/* combined_plates/; else echo "Warning: Directory $PLATE_DIR does not exist. Skipping..."; fi; done

for plate in $(seq 1 "$NUM_PLATES"); do
    PLATE_DIR="plate_${plate}"

    if [ -d "$PLATE_DIR" ]; then
        cp "$PLATE_DIR"/* combined_plates/
    else
        echo "Warning: Directory $PLATE_DIR does not exist. Skipping..."
    fi
done

cd "$BASE_DIR/stacksoutput/combined_plates"

# Delete the .rem. files in the combined_plates folder 
rm -r *rem*

# Remove the folders with small sizes, and put them in a folder called "removed_zipped"
mkdir -p ./removed_zipped
find -type f -exec du -sb {} \; | awk '$1 < 100' | cut -f2- | xargs -I {} mv {} ./removed_zipped

# Move all the fq.gz files into a new folder, so that this new folder contains only sample files for further processing (excluding txt files and others)
mkdir -p ./ready
mv *.fq.gz ./ready

############################################################################################################################################
# Since some samples were removed (small file size, quality etc.), we need to create an updated list of samples with population information

# extract the sample names from the “ready” folder, so that you can create a population file with each sample name, and the population it comes from. 
# Here, we’re keeping the sample names, excluding the last .1 or .2 from the name, and then deleting the resulting duplicate names. E.g. there will be CI11.1.1.1 and
# CI11.1.1.2 for read 1 and read 2. After deleting the .1 and .2, we’ll have two CI11.1.1 names → that’s why we delete duplicates

find ./ready -type f -name '*.fq.gz' | sed 's|.*/||; s/\.fq\.gz$//' | sed 's/\.[0-9]*$//' | sort -u > samplenames.txt

# Now sort through the file with population assignments for all samples (pops_all.txt), and allocate the correct population group to the right samples

# first sort the pops_all.txt file

sort "$BASE_DIR/barcodes/pops_all.txt" -o "$BASE_DIR/barcodes/pops_all.txt"

# process other population files if desired, for alternative predefined groupings
#sort "$BASE_DIR/barcodes/pops_all_sa.txt" -o "$BASE_DIR/stacksoutput/barcodes/pops_all_sa.txt"
 
# now join the population group names in pops_all.txt to the sample names in samplenames.txt
# write the results to bothplates_pops.txt in the barcodes/ folder
# -t $'\t' ensures a tab space between the sample name and population name assigned

# even if there was only one plate, the output file is called "both_plates_pops.txt" -> leave as is to keep it simple
join -t $'\t' "$BASE_DIR/barcodes/pops_all.txt" "$BASE_DIR/stacksoutput/combined_plates/samplenames.txt" > "$BASE_DIR/barcodes/bothplates_pops.txt"

##############################################################