#!/bin/bash

############################################################################################
# INDEX THE REFERENCE genome
# This script needs to be run only once
############################################################################################

############################################################################################
# Submit this script as a job using:
# qsub -v REFERENCE_INDEX="/mnt/lustre/users/cvansteenderen/RADseq_crystallinum/data/ref_genome/ncbi_dataset/data/GCA_030267885.1" index_refgenome.job
############################################################################################

#PBS -l select=1:ncpus=24:mpiprocs=24
#PBS -P CBBI1682
#PBS -q serial
#PBS -l walltime=4:00:00
#PBS -o /mnt/lustre/users/cvansteenderen/RADseq_crystallinum/data/ref_genome/stdout.txt
#PBS -e /mnt/lustre/users/cvansteenderen/RADseq_crystallinum/data/ref_genome/stderr.txt
#PBS -N bowtie2_indexing
#PBS -M vsteenderen@gmail.com
#PBS -m abe

##############################################################

module add chpc/BIOMODULES
module add bowtie2

cd "$REFERENCE_INDEX"

##############################################################
# assign indexes to the reference genome scaffolds
##############################################################

# find the .fna file in the folder
fna_file=$(find . -maxdepth 1 -name "*.fna" | head -n 1)

bowtie2-build --threads 4 "$fna_file" reference_index
