#!/bin/bash

############################################################################################
# RUN Stacks USING DENOVO APPROACH (NO REF GENOME)

# Make sure that there is a barcodes/ folder in your HOME_DIR, that contains all sample names 
# and pop assignments. This should automatically be there if you have only been working with
# one project. But, if this is combined from different projects, then manually combine the 
# bothplates_pops.txt files from each project into one big one

############################################################################################
# Submit this script as a job using:

# qsub -v SAMPLE_DIR="/mnt/lustre/users/cvansteenderen/RADseq_crystallinum/data/combined_data_all_spp/ready",BARCODES_DIR="/mnt/lustre/users/cvansteenderen/RADseq_crystallinum/data/combined_data_all_spp/barcodes" 2_align_and_stacks_denovo.job

############################################################################################

#PBS -l select=1:ncpus=12
#PBS -P CBBI1682
#PBS -q serial
#PBS -l walltime=48:00:00
#PBS -o /mnt/lustre/users/cvansteenderen/RADseq_crystallinum/data/combined_data_all_spp/denovo_stdout.txt
#PBS -e /mnt/lustre/users/cvansteenderen/RADseq_crystallinum/data/combined_data_all_spp/denovo_stderr.txt
#PBS -N stacks_denovo
#PBS -M vsteenderen@gmail.com
#PBS -m abe

##############################################################

module add chpc/BIOMODULES
module add stacks

cd "$SAMPLE_DIR"

##############################################################
# Run Stacks with these settings
##############################################################

# -m 3 = the minimum number of identical raw reads required to create a stack
# -n 4 = number of mismatches allowed between stacks between individuals
# -M 3 = number of mismatches allowed between stacks within individuals
# -T 8 = number of threads
# --rm-pcr-duplicates = remove all but one set of read pairs of the same sample that have the same insert length
# --paired = after assembling RAD loci, assemble contigs for each locus from paired-end reads
# --min-samples-per-pop 0.75 = minimum percentage of individuals in a population required to process a locus for that population
# --min-populations 2 = minimum number of populations a locus must be present in to process a locus. We have a total of 8 population groups in this data
# -X "populations:--fstats" enable SNP and haplotype-based F statistics

##############################################################
# STACKS: assemble reads 
##############################################################

SAMPLE_FOLDER="$SAMPLE_DIR"
POPS_FILE="$BARCODES_DIR/bothplates_pops.txt"

mkdir -p "$SAMPLE_DIR/stacksoutput_denovo"

OUTPUT_FOLDER="$SAMPLE_DIR/stacksoutput_denovo"

denovo_map.pl -m 5 -n 3 -M 2 -T 10 -o "$OUTPUT_FOLDER" --popmap "$POPS_FILE" --samples "$SAMPLE_FOLDER" --rm-pcr-duplicates --paired --min-samples-per-pop 0.75 --min-populations 2 -X "populations:--fstats"

##############################################################
# STACKS: populations
##############################################################

mkdir -p "$SAMPLE_DIR/stacksoutput_denovo/populations"

populations -P "$SAMPLE_DIR/stacksoutput_denovo" -O "$SAMPLE_DIR/stacksoutput_denovo/populations" --popmap "$SAMPLE_FOLDER" -r 0.75 -f p_value -t 12 --hwe --fstats --genepop --plink --phylip --vcf --vcf-all
