library(SNPfiltR)
library(vcfR)
library(adegenet)
library(hierfstat)
library(pegas)
library(poppr)
library(PopGenReport)
library(ggplot2)

setwd("D:/RADseq/crystallinum")
orig = vcfR::read.vcfR("populations/populations.snps.vcf")

# make a copy
cryo.snps = orig

popmap.broad = read.table("populations/broad_pops.txt", header = TRUE)
popmap.broad

popmap.country = read.table("populations/country_pops.txt", header = TRUE)
popmap.country

popmap.site = read.table("populations/site_pops.txt", header = TRUE)
popmap.site

#visualize distributions
SNPfiltR::hard_filter(vcfR=cryo.snps)

# ***** Object of Class vcfR *****
#   95 samples
# 12779 CHROMs
# 89,042 variants
# Object size: 296 Mb
# 44.9 percent missing data
# *****        *****         *****

# 22.41% of genotypes fall below a read depth of 5 and were converted to NA
# 4.76% of genotypes fall below a genotype quality of 35 and were converted to NA
cryo.snps = SNPfiltR::hard_filter(vcfR=cryo.snps, depth = 5, gq = 35)
cryo.snps = SNPfiltR::filter_allele_balance(cryo.snps)

# dashed line indicates a mean depth across all SNPs of 37.2
SNPfiltR::max_depth(cryo.snps)

# maxdepth cutoff is specified, filtered vcfR object will be returned
# 6.68% of SNPs were above a mean depth of 100 and were removed from the vcf
cryo.snps = SNPfiltR::max_depth(cryo.snps, maxdepth = 100)
cryo.snps

SNPfiltR::missing_by_sample(vcfR=cryo.snps, popmap = popmap.broad)

# 4 samples are above a 0.9 missing data cutoff, and were removed from VCF
cryo.snps = SNPfiltR::missing_by_sample(vcfR=cryo.snps, cutoff = .9)

#subset popmap to only include retained individuals
popmap.broad = popmap.broad[popmap.broad$id %in% colnames(cryo.snps@gt),]
popmap.country = popmap.country[popmap.country$id %in% colnames(cryo.snps@gt),]
popmap.site = popmap.site[popmap.site$id %in% colnames(cryo.snps@gt),]

#remove invariant sites generated by dropping individuals
# 26.68% of SNPs fell below a minor allele count of 1 and were removed from the VCF
cryo.snps = SNPfiltR::min_mac(cryo.snps, min.mac = 1)

miss = SNPfiltR::assess_missing_data_pca(vcfR=cryo.snps, 
                popmap = popmap.broad, thresholds = .8, clustering = FALSE)

# Picking joint bandwidth of 0.0483
SNPfiltR::missing_by_snp(cryo.snps)

miss = SNPfiltR::assess_missing_data_pca(vcfR=cryo.snps, popmap = popmap.broad, 
                               thresholds = c(.6, .65, .7), clustering = FALSE)

cryo.snps = SNPfiltR::missing_by_snp(cryo.snps, cutoff = .80)

cryo.snps

cryo.snps.mac = SNPfiltR::min_mac(vcfR = cryo.snps, min.mac = 2)

#assess clustering without MAC cutoff
miss = SNPfiltR::assess_missing_data_tsne(cryo.snps, popmap.broad, 
                                          clustering = FALSE)
#assess clustering with MAC cutoff
miss = SNPfiltR::assess_missing_data_tsne(cryo.snps.mac, popmap.broad, 
                                          clustering = FALSE)

#plot depth per snp and per sample
dp = vcfR::extract.gt(cryo.snps, element = "DP", as.numeric=TRUE)
vcfR::heatmap.bp(dp, rlabels = FALSE)

#plot genotype quality per snp and per sample
gq = vcfR::extract.gt(cryo.snps, element = "GQ", as.numeric=TRUE)
vcfR::heatmap.bp(gq, rlabels = FALSE)

cryo.snps

# original file: 95 samples, 89,042 SNPs
# after filtering: 91 samples, 15,786 SNPs (9% missing data)
# ~6X smaller

vcfR::write.vcf(cryo.snps, "populations/populations.snps.filtered.vcf")
